Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
spectrum = rfft(spots)

plt.figure()
plt.plot(abs(spectrum))
plt.savefig("fixed.png")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_13724/715805462.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mspectrum[0m [0;34m=[0m [0mrfft[0m[0;34m([0m[0mspots[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mabs[0m[0;34m([0m[0mspectrum[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mplt[0m[0;34m.[0m[0msavefig[0m[0;34m([0m[0;34m"fixed.png"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<__array_function__ internals>[0m in [0;36mrfft[0;34m(*args, **kwargs)[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/fft/_pocketfft.py[0m in [0;36mrfft[0;34m(a, n, axis, norm)[0m
[1;32m    406[0m     [0;32mif[0m [0mn[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    407[0m         [0mn[0m [0;34m=[0m [0ma[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0maxis[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 408[0;31m     [0minv_norm[0m [0;34m=[0m [0m_get_forward_norm[0m[0;34m([0m[0mn[0m[0;34m,[0m [0mnorm[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    409[0m     [0moutput[0m [0;34m=[0m [0m_raw_fft[0m[0;34m([0m[0ma[0m[0;34m,[0m [0mn[0m[0;34m,[0m [0maxis[0m[0;34m,[0m [0;32mTrue[0m[0;34m,[0m [0;32mTrue[0m[0;34m,[0m [0minv_norm[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    410[0m     [0;32mreturn[0m [0moutput[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/fft/_pocketfft.py[0m in [0;36m_get_forward_norm[0;34m(n, norm)[0m
[1;32m     78[0m [0;32mdef[0m [0m_get_forward_norm[0m[0;34m([0m[0mn[0m[0;34m,[0m [0mnorm[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     79[0m     [0;32mif[0m [0mn[0m [0;34m<[0m [0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 80[0;31m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34mf"Invalid number of FFT data points ({n}) specified."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     81[0m [0;34m[0m[0m
[1;32m     82[0m     [0;32mif[0m [0mnorm[0m [0;32mis[0m [0;32mNone[0m [0;32mor[0m [0mnorm[0m [0;34m==[0m [0;34m"backward"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: Invalid number of FFT data points (0) specified.
ValueError: Invalid number of FFT data points (0) specified.

